name = "fsshowdown-matchmaker"
main = "src/index.js"
compatibility_date = "2026-09-11"

[[d1_databases]]
binding = "DB"
database_name = "fsshowdown"
database_id = "57a8679b-4ada-4032-b712-70bc0ef629dd"

[[durable_objects.bindings]]
name = "MATCHMAKER"
class_name = "Matchmaker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Matchmaker"]

[triggers]
crons = ["0 3 * * *"]
